# Generated by Django 4.2.16 on 2024-10-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
